# Generated by Django 5.0.6 on 2024-07-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('box_units', models.PositiveIntegerField(blank=True, null=True)),
                ('kwh', models.FloatField(blank=True, null=True)),
                ('flow', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
