# Generated by Django 5.0.6 on 2024-08-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwh_cost', models.FloatField(blank=True, null=True)),
                ('m3_cost', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
